POST http://localhost:3333/videos
Content-Type: application/json
Content-Accept-Language: pt-br

{
    "title": "my video",
    "description": "My video description",
    "url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ"        
}

### 
GET http://localhost:3333/videos?search=node

###
GET http://localhost:3333/videos

###
PUT http://localhost:3333/videos/55a5523a-5d43-4f5c-8be8-291695a82347
Content-Type: application/json
Content-Accept-Language: pt-br

{
    "title": "Video updated",
    "description": "My video description",
    "url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ"        
}

###
DELETE http://localhost:3333/videos/e4f00073-1397-4709-93a8-ae54bc332d48